swagger: "2.0"
info:
  title: WalletNode REST API
  version: "1.0"
host: localhost:8080
consumes:
  - application/json
  - application/xml
  - application/gob
produces:
  - application/json
  - application/xml
  - application/gob
paths:
  /artworks/register:
    get:
      tags:
        - artworks
      summary: Returns list of tasks
      description: List of all tasks.
      operationId: artworks#registerTasks
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ArtworksTaskResponseTinyCollection'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTasksInternalServerErrorResponseBody'
      schemes:
        - http
    post:
      tags:
        - artworks
      summary: Registers a new artwork
      description: Runs a new registration process for the new artwork.
      operationId: artworks#register
      parameters:
        - name: RegisterRequestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/ArtworksRegisterRequestBody'
            required:
              - image_id
              - artist_name
              - name
              - issued_copies
              - artist_pastelid
              - artist_pastelid_passphrase
              - spendable_address
              - maximum_fee
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/ArtworksRegisterResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksRegisterBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterInternalServerErrorResponseBody'
      schemes:
        - http
  /artworks/register/{taskId}:
    get:
      tags:
        - artworks
      summary: Find task by ID
      description: Returns a single task.
      operationId: artworks#registerTask
      parameters:
        - name: taskId
          in: path
          description: Task ID of the registration process
          required: true
          type: string
          maxLength: 8
          minLength: 8
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskNotFoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskInternalServerErrorResponseBody'
      schemes:
        - http
  /artworks/register/{taskId}/state:
    get:
      tags:
        - artworks
      summary: Streams state by task ID
      description: Streams the state of the registration process.
      operationId: artworks#registerTaskState
      parameters:
        - name: taskId
          in: path
          description: Task ID of the registration process
          required: true
          type: string
          maxLength: 8
          minLength: 8
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskStateResponseBody'
            required:
              - date
              - status
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskStateNotFoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksRegisterTaskStateInternalServerErrorResponseBody'
      schemes:
        - ws
  /artworks/register/upload:
    post:
      tags:
        - artworks
      summary: Uploads an image
      description: Upload the image that is used when registering a new artwork.
      operationId: artworks#uploadImage
      consumes:
        - multipart/form-data
      parameters:
        - name: UploadImageRequestBody
          in: formData
          required: true
          schema:
            $ref: '#/definitions/ArtworksUploadImageRequestBody'
            required:
              - file
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksUploadImageInternalServerErrorResponseBody'
      schemes:
        - http
  /artworks/search/{term}:
    get:
      tags:
        - artworks
      summary: search artworks
      description: Search artwork request
      operationId: artworks#searchRequest
      parameters:
        - name: term
          in: path
          description: artwork search request
          required: true
          type: string
      responses:
        "101":
          description: Switching Protocols response.
          schema:
            $ref: '#/definitions/ArtworksSearchRequestResponseBody'
            required:
              - artist_name
              - name
              - issued_copies
              - artist_pastelid
              - artist_pastelid_passphrase
              - spendable_address
              - maximum_fee
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/ArtworksSearchRequestBadRequestResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/ArtworksSearchRequestInternalServerErrorResponseBody'
      schemes:
        - ws
definitions:
  ArtworkTicketResponse:
    title: ArtworkTicketResponse
    type: object
    properties:
      artist_name:
        type: string
        description: Name of the artist
        example: Leonardo da Vinci
        maxLength: 256
      artist_pastelid:
        type: string
        description: Artist's PastelID
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        pattern: ^[a-zA-Z0-9]+$
        minLength: 86
        maxLength: 86
      artist_pastelid_passphrase:
        type: string
        description: Passphrase of the artist's PastelID
        example: qwerasdf1234
      artist_website_url:
        type: string
        description: Artist website URL
        example: https://www.leonardodavinci.net
        maxLength: 256
      description:
        type: string
        description: Description of the artwork
        example: The Mona Lisa is an oil painting by Italian artist, inventor, and
          writer Leonardo da Vinci. Likely completed in 1506, the piece features a
          portrait of a seated woman set against an imaginary landscape.
        maxLength: 1024
      issued_copies:
        type: integer
        description: Number of copies issued
        default: 1
        example: 1
        minimum: 1
        maximum: 1000
      keywords:
        type: string
        description: Keywords
        example: Renaissance, sfumato, portrait
        maxLength: 256
      maximum_fee:
        type: number
        description: Used to find a suitable masternode with a fee equal or less
        default: 1
        example: 100
        minimum: 1e-05
      name:
        type: string
        description: Name of the artwork
        example: Mona Lisa
        maxLength: 256
      series_name:
        type: string
        description: Series name
        example: Famous artist
        maxLength: 256
      spendable_address:
        type: string
        description: Spendable address
        example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        pattern: ^[a-zA-Z0-9]+$
        minLength: 35
        maxLength: 35
      youtube_url:
        type: string
        description: Artwork creation video youtube URL
        example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        maxLength: 128
    description: Ticket of the registration artwork
    example:
      artist_name: Leonardo da Vinci
      artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      artist_pastelid_passphrase: qwerasdf1234
      artist_website_url: https://www.leonardodavinci.net
      description: The Mona Lisa is an oil painting by Italian artist, inventor, and
        writer Leonardo da Vinci. Likely completed in 1506, the piece features a portrait
        of a seated woman set against an imaginary landscape.
      issued_copies: 1
      keywords: Renaissance, sfumato, portrait
      maximum_fee: 100
      name: Mona Lisa
      series_name: Famous artist
      spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
      youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
    required:
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
  ArtworkTicketResponseBody:
    title: ArtworkTicketResponseBody
    type: object
    properties:
      artist_name:
        type: string
        description: Name of the artist
        example: Leonardo da Vinci
        maxLength: 256
      artist_pastelid:
        type: string
        description: Artist's PastelID
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        pattern: ^[a-zA-Z0-9]+$
        minLength: 86
        maxLength: 86
      artist_pastelid_passphrase:
        type: string
        description: Passphrase of the artist's PastelID
        example: qwerasdf1234
      artist_website_url:
        type: string
        description: Artist website URL
        example: https://www.leonardodavinci.net
        maxLength: 256
      description:
        type: string
        description: Description of the artwork
        example: The Mona Lisa is an oil painting by Italian artist, inventor, and
          writer Leonardo da Vinci. Likely completed in 1506, the piece features a
          portrait of a seated woman set against an imaginary landscape.
        maxLength: 1024
      issued_copies:
        type: integer
        description: Number of copies issued
        default: 1
        example: 1
        minimum: 1
        maximum: 1000
      keywords:
        type: string
        description: Keywords
        example: Renaissance, sfumato, portrait
        maxLength: 256
      maximum_fee:
        type: number
        description: Used to find a suitable masternode with a fee equal or less
        default: 1
        example: 100
        minimum: 1e-05
      name:
        type: string
        description: Name of the artwork
        example: Mona Lisa
        maxLength: 256
      series_name:
        type: string
        description: Series name
        example: Famous artist
        maxLength: 256
      spendable_address:
        type: string
        description: Spendable address
        example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        pattern: ^[a-zA-Z0-9]+$
        minLength: 35
        maxLength: 35
      youtube_url:
        type: string
        description: Artwork creation video youtube URL
        example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        maxLength: 128
    description: Ticket of the registration artwork
    example:
      artist_name: Leonardo da Vinci
      artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      artist_pastelid_passphrase: qwerasdf1234
      artist_website_url: https://www.leonardodavinci.net
      description: The Mona Lisa is an oil painting by Italian artist, inventor, and
        writer Leonardo da Vinci. Likely completed in 1506, the piece features a portrait
        of a seated woman set against an imaginary landscape.
      issued_copies: 1
      keywords: Renaissance, sfumato, portrait
      maximum_fee: 100
      name: Mona Lisa
      series_name: Famous artist
      spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
      youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
    required:
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
  ArtworksRegisterBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: register_BadRequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: register_InternalServerError_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterRequestBody:
    title: ArtworksRegisterRequestBody
    type: object
    properties:
      artist_name:
        type: string
        description: Name of the artist
        example: Leonardo da Vinci
        maxLength: 256
      artist_pastelid:
        type: string
        description: Artist's PastelID
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        pattern: ^[a-zA-Z0-9]+$
        minLength: 86
        maxLength: 86
      artist_pastelid_passphrase:
        type: string
        description: Passphrase of the artist's PastelID
        example: qwerasdf1234
      artist_website_url:
        type: string
        description: Artist website URL
        example: https://www.leonardodavinci.net
        maxLength: 256
      description:
        type: string
        description: Description of the artwork
        example: The Mona Lisa is an oil painting by Italian artist, inventor, and
          writer Leonardo da Vinci. Likely completed in 1506, the piece features a
          portrait of a seated woman set against an imaginary landscape.
        maxLength: 1024
      image_id:
        type: string
        description: Uploaded image ID
        example: VK7mpAqZ
        minLength: 8
        maxLength: 8
      issued_copies:
        type: integer
        description: Number of copies issued
        default: 1
        example: 1
        minimum: 1
        maximum: 1000
      keywords:
        type: string
        description: Keywords
        example: Renaissance, sfumato, portrait
        maxLength: 256
      maximum_fee:
        type: number
        description: Used to find a suitable masternode with a fee equal or less
        default: 1
        example: 100
        minimum: 1e-05
      name:
        type: string
        description: Name of the artwork
        example: Mona Lisa
        maxLength: 256
      series_name:
        type: string
        description: Series name
        example: Famous artist
        maxLength: 256
      spendable_address:
        type: string
        description: Spendable address
        example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        pattern: ^[a-zA-Z0-9]+$
        minLength: 35
        maxLength: 35
      youtube_url:
        type: string
        description: Artwork creation video youtube URL
        example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        maxLength: 128
    example:
      artist_name: Leonardo da Vinci
      artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      artist_pastelid_passphrase: qwerasdf1234
      artist_website_url: https://www.leonardodavinci.net
      description: The Mona Lisa is an oil painting by Italian artist, inventor, and
        writer Leonardo da Vinci. Likely completed in 1506, the piece features a portrait
        of a seated woman set against an imaginary landscape.
      image_id: VK7mpAqZ
      issued_copies: 1
      keywords: Renaissance, sfumato, portrait
      maximum_fee: 100
      name: Mona Lisa
      series_name: Famous artist
      spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
      youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
    required:
      - image_id
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
  ArtworksRegisterResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.register; view=default'
    type: object
    properties:
      task_id:
        type: string
        description: Task ID of the registration process
        example: n6Qn6TFM
        minLength: 8
        maxLength: 8
    description: RegisterResponseBody result type (default view)
    example:
      task_id: n6Qn6TFM
    required:
      - task_id
  ArtworksRegisterTaskInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerTask_InternalServerError_response_body result type (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterTaskNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerTask_NotFound_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterTaskResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.register.task; view=default'
    type: object
    properties:
      id:
        type: string
        description: JOb ID of the registration process
        example: n6Qn6TFM
        minLength: 8
        maxLength: 8
      states:
        type: array
        items:
          $ref: '#/definitions/TaskStateResponseBody'
        description: List of states from the very beginning of the process
        example:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
      status:
        type: string
        description: Status of the registration process
        example: Task Started
        enum:
          - Task Started
          - Connected
          - Image Uploaded
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error FGPT Not Match
          - Task Rejected
          - Task Completed
      ticket:
        $ref: '#/definitions/ArtworkTicketResponseBody'
      txid:
        type: string
        description: txid
        example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        minLength: 64
        maxLength: 64
    description: RegisterTaskResponseBody result type (default view)
    example:
      id: n6Qn6TFM
      states:
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
        - date: 2006-01-02T15:04:05Z07:00
          status: Task Started
      status: Task Started
      ticket:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_pastelid_passphrase: qwerasdf1234
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        issued_copies: 1
        keywords: Renaissance, sfumato, portrait
        maximum_fee: 100
        name: Mona Lisa
        series_name: Famous artist
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
    required:
      - id
      - status
      - ticket
  ArtworksRegisterTaskStateInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerTaskState_InternalServerError_response_body result type (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterTaskStateNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: registerTaskState_NotFound_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksRegisterTaskStateResponseBody:
    title: ArtworksRegisterTaskStateResponseBody
    type: object
    properties:
      date:
        type: string
        description: Date of the status creation
        example: 2006-01-02T15:04:05Z07:00
      status:
        type: string
        description: Status of the registration process
        example: Task Started
        enum:
          - Task Started
          - Connected
          - Image Uploaded
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error FGPT Not Match
          - Task Rejected
          - Task Completed
    example:
      date: 2006-01-02T15:04:05Z07:00
      status: Task Started
    required:
      - date
      - status
  ArtworksRegisterTasksInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: registerTasks_InternalServerError_response_body result type (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksSearchRequestBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: searchRequest_BadRequest_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksSearchRequestInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: searchRequest_InternalServerError_response_body result type (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksSearchRequestResponseBody:
    title: ArtworksSearchRequestResponseBody
    type: object
    properties:
      artist_name:
        type: string
        description: Name of the artist
        example: Leonardo da Vinci
        maxLength: 256
      artist_pastelid:
        type: string
        description: Artist's PastelID
        example: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        pattern: ^[a-zA-Z0-9]+$
        minLength: 86
        maxLength: 86
      artist_pastelid_passphrase:
        type: string
        description: Passphrase of the artist's PastelID
        example: qwerasdf1234
      artist_website_url:
        type: string
        description: Artist website URL
        example: https://www.leonardodavinci.net
        maxLength: 256
      description:
        type: string
        description: Description of the artwork
        example: The Mona Lisa is an oil painting by Italian artist, inventor, and
          writer Leonardo da Vinci. Likely completed in 1506, the piece features a
          portrait of a seated woman set against an imaginary landscape.
        maxLength: 1024
      issued_copies:
        type: integer
        description: Number of copies issued
        default: 1
        example: 1
        minimum: 1
        maximum: 1000
      keywords:
        type: string
        description: Keywords
        example: Renaissance, sfumato, portrait
        maxLength: 256
      maximum_fee:
        type: number
        description: Used to find a suitable masternode with a fee equal or less
        default: 1
        example: 100
        minimum: 1e-05
      name:
        type: string
        description: Name of the artwork
        example: Mona Lisa
        maxLength: 256
      series_name:
        type: string
        description: Series name
        example: Famous artist
        maxLength: 256
      spendable_address:
        type: string
        description: Spendable address
        example: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        pattern: ^[a-zA-Z0-9]+$
        minLength: 35
        maxLength: 35
      youtube_url:
        type: string
        description: Artwork creation video youtube URL
        example: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        maxLength: 128
    example:
      artist_name: Leonardo da Vinci
      artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
      artist_pastelid_passphrase: qwerasdf1234
      artist_website_url: https://www.leonardodavinci.net
      description: The Mona Lisa is an oil painting by Italian artist, inventor, and
        writer Leonardo da Vinci. Likely completed in 1506, the piece features a portrait
        of a seated woman set against an imaginary landscape.
      issued_copies: 1
      keywords: Renaissance, sfumato, portrait
      maximum_fee: 100
      name: Mona Lisa
      series_name: Famous artist
      spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
      youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
    required:
      - artist_name
      - name
      - issued_copies
      - artist_pastelid
      - artist_pastelid_passphrase
      - spendable_address
      - maximum_fee
  ArtworksTaskResponseTinyCollection:
    title: 'Mediatype identifier: application/vnd.artwork.register.task; type=collection;
      view=tiny'
    type: array
    items:
      $ref: '#/definitions/TaskResponseTiny'
    description: ArtworksTaskResponseTinyCollection is the result type for an array
      of TaskResponseTiny (default view)
    example:
      - id: n6Qn6TFM
        states:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: n6Qn6TFM
        states:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
      - id: n6Qn6TFM
        states:
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
          - date: 2006-01-02T15:04:05Z07:00
            status: Task Started
        status: Task Started
        ticket:
          artist_name: Leonardo da Vinci
          artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
          artist_pastelid_passphrase: qwerasdf1234
          artist_website_url: https://www.leonardodavinci.net
          description: The Mona Lisa is an oil painting by Italian artist, inventor,
            and writer Leonardo da Vinci. Likely completed in 1506, the piece features
            a portrait of a seated woman set against an imaginary landscape.
          issued_copies: 1
          keywords: Renaissance, sfumato, portrait
          maximum_fee: 100
          name: Mona Lisa
          series_name: Famous artist
          spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
          youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
        txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
  ArtworksUploadImageBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: uploadImage_BadRequest_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksUploadImageInternalServerErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: uploadImage_InternalServerError_response_body result type (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
  ArtworksUploadImageRequestBody:
    title: ArtworksUploadImageRequestBody
    type: object
    properties:
      file:
        type: string
        description: File to upload
        example:
          - 84
          - 111
          - 116
          - 97
          - 109
          - 32
          - 101
          - 115
          - 116
          - 32
          - 117
          - 110
          - 100
          - 101
          - 32
          - 113
          - 117
          - 105
          - 97
          - 32
          - 101
          - 105
          - 117
          - 115
          - 46
        format: byte
      filename:
        type: string
        description: For internal use
    example:
      file:
        - 72
        - 97
        - 114
        - 117
        - 109
        - 32
        - 105
        - 108
        - 108
        - 117
        - 109
        - 46
    required:
      - file
  ArtworksUploadImageResponseBody:
    title: 'Mediatype identifier: application/vnd.artwork.upload-image; view=default'
    type: object
    properties:
      expires_in:
        type: string
        description: Image expiration
        example: 2006-01-02T15:04:05Z07:00
        format: date-time
      image_id:
        type: string
        description: Uploaded image ID
        example: VK7mpAqZ
        minLength: 8
        maxLength: 8
    description: UploadImageResponseBody result type (default view)
    example:
      expires_in: 2006-01-02T15:04:05Z07:00
      image_id: VK7mpAqZ
    required:
      - image_id
      - expires_in
  TaskResponseTiny:
    title: 'Mediatype identifier: application/vnd.artwork.register.task; view=default'
    type: object
    properties:
      id:
        type: string
        description: JOb ID of the registration process
        example: n6Qn6TFM
        minLength: 8
        maxLength: 8
      status:
        type: string
        description: Status of the registration process
        example: Task Started
        enum:
          - Task Started
          - Connected
          - Image Uploaded
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error FGPT Not Match
          - Task Rejected
          - Task Completed
      ticket:
        $ref: '#/definitions/ArtworkTicketResponse'
      txid:
        type: string
        description: txid
        example: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
        minLength: 64
        maxLength: 64
    description: TaskResponse result type (tiny view) (default view)
    example:
      id: n6Qn6TFM
      status: Task Started
      ticket:
        artist_name: Leonardo da Vinci
        artist_pastelid: jXYJud3rmrR1Sk2scvR47N4E4J5Vv48uCC6se2nzHrBRdjaKj3ybPoi1Y2VVoRqi1GnQrYKjSxQAC7NBtvtEdS
        artist_pastelid_passphrase: qwerasdf1234
        artist_website_url: https://www.leonardodavinci.net
        description: The Mona Lisa is an oil painting by Italian artist, inventor,
          and writer Leonardo da Vinci. Likely completed in 1506, the piece features
          a portrait of a seated woman set against an imaginary landscape.
        issued_copies: 1
        keywords: Renaissance, sfumato, portrait
        maximum_fee: 100
        name: Mona Lisa
        series_name: Famous artist
        spendable_address: PtiqRXn2VQwBjp1K8QXR2uW2w2oZ3Ns7N6j
        youtube_url: https://www.youtube.com/watch?v=0xl6Ufo4ZX0
      txid: 576e7b824634a488a2f0baacf5a53b237d883029f205df25b300b87c8877ab58
    required:
      - id
      - status
      - ticket
  TaskStateResponseBody:
    title: TaskStateResponseBody
    type: object
    properties:
      date:
        type: string
        description: Date of the status creation
        example: 2006-01-02T15:04:05Z07:00
      status:
        type: string
        description: Status of the registration process
        example: Task Started
        enum:
          - Task Started
          - Connected
          - Image Uploaded
          - Ticket Accepted
          - Ticket Registered
          - Ticket Activated
          - Error Insufficient Fee
          - Error FGPT Not Match
          - Task Rejected
          - Task Completed
    example:
      date: 2006-01-02T15:04:05Z07:00
      status: Task Started
    required:
      - date
      - status
